<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Dropworks.Smoke</AssemblyName>
    <RootNamespace>Dropworks.Smoke</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Dropworks/Dropworks.csproj" />
  </ItemGroup>

</Project>
